spring.application.name=kotouslugi-api
spring.profiles.active=postgres

# UTF-8 for HTTP responses
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.servlet.encoding.force-request=true
server.servlet.encoding.force-response=true

# JPA common
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# SQL init common
spring.jpa.defer-datasource-initialization=true
spring.sql.init.encoding=UTF-8
