spring.application.name=kotouslugi-api


# 1. НАСТРОЙКИ БАЗЫ ДАННЫХ (H2)

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true


# 2. НАСТРОЙКИ HIBERNATE (Создание таблиц по @Entity)


spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true


# 3. НАСТРОЙКИ ИНИЦИАЛИЗАЦИИ ДАННЫХ (data.sql)

spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:db/data.sql
spring.sql.init.encoding=UTF-8

# 4. ЛОГИРОВАНИЕ (для отладки)

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.generate_statistics=true
logging.level.org.hibernate.stat=debug
